spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ecommerce_inventory}
    username: ${DB_USER:ecommerce_user}
    password: ${DB_PASSWORD:ecommerce_password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: ${SERVER_PORT:8083}

logging:
  level:
    com.alexisardaya: INFO
    org.springframework.web: WARN
    org.springframework.kafka: INFO

